#!/bin/sh
### BEGIN INIT INFO
# Provides:          shuttersiot
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Home IOT RAT
# Description:       Home IOT Shutters
# Author:            vukadinoff@gmail.com
# Version:           1.0
### END INIT INFO


case "$1" in
    start)
        echo -n "Starting Shutters IOT: "
        cd /usr/local/bin/home-iot/shutters/
        export PYTHONUNBUFFERED=True
        nohup python ShuttersMqtt.py  >> /var/log/shuttersiot.log 2>&1  &
        sleep 1
        echo "done"
        ;;
    stop)
        echo -n "Killing HomeIOT server:"
        ps ax | grep "ShuttersMqtt.py" | awk '{ print $1 }' | xargs kill -15 >/dev/null 2>&1
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0

